# Generated by Django 2.2 on 2019-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_sub_category',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='backends.ItemSubCategory', verbose_name='子类'),
        ),
    ]
