# Generated by Django 2.2 on 2019-09-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0002_auto_20190905_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='none', max_length=100, verbose_name='品名')),
                ('item_price', models.DecimalField(decimal_places=3, default='none', max_digits=100, verbose_name='价格')),
                ('item_stoke', models.IntegerField(default=9999, verbose_name='库存')),
            ],
        ),
    ]
